name: RSS to MISP Feed

on:
  schedule:
    - cron: '0 * * * *'  # Runs hourly
  workflow_dispatch:

jobs:
  generate-feed:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download SpaCy model
      run: python -m spacy download en_core_web_sm
    
    - name: Run RSS Collector
      run: python rss_ioc_collector.py
    
    - name: Convert to MISP Feed
      run: |
        python utils/misp_push.py output.json misp_feed/events/rss-feed.json

    - name: Commit and push updated feed
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        # Clean working directory by stashing unintended local changes (e.g., .pyc)
        git stash --include-untracked

        # Pull remote changes safely
        git pull --rebase

        # Restore stashed changes
        git stash pop || true

        # Only stage the intended file
        git add misp_feed/events/rss-feed.json

        # Commit if there are actual changes
        git diff --cached --quiet || git commit -m "Update MISP feed: new IOCs from RSS collector"

        # Push with authentication
        git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
        git push

