name: RSS to MISP Feed

on:
  schedule:
    - cron: '0 * * * *'  # Runs hourly
  workflow_dispatch:

jobs:
  generate-feed:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download SpaCy model
      run: python -m spacy download en_core_web_sm
    
    - name: Run RSS Collector
      run: python rss_ioc_collector.py
    
    - name: Convert to MISP Feed
      run: |
        python utils/misp_push.py output.json misp_feed/events/rss-feed.json

    - name: Commit and push updated feed
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        # Stage changes (if any)
        git add .

        # Commit any changes with a default message if needed
        git commit -m "Temporary commit before pulling updates" || echo "No changes to commit"

        # Pull the latest changes with rebase
        git pull --rebase

        # Now commit the MISP feed change
        git add misp_feed/events/rss-feed.json
        git commit -m "Update MISP feed: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes to commit"

        # Push the changes
        git push
