name: RSS to MISP Feed

on:
  schedule:
    - cron: '0 * * * *'   # hourly
  workflow_dispatch:

jobs:
  build-feed:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Validate config.json
        run: |
          jq empty config/config.json || exit 1

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download spaCy model
        run: python -m spacy download en_core_web_sm

      - name: Ensure logs directory exists
        run: mkdir -p logs

      - name: Run collector & build feed
        run: |
          set -e
          python rss_ioc_collector.py > ./logs/workflow.log 2>&1

      - name: Print logs for debugging
        if: failure()
        run: cat ./logs/workflow.log

      - name: Debug file structure
        run: |
          echo "Listing all files in the working directory:"
          ls -R
          echo "Listing files in the misp_feed directory:"
          ls misp_feed

      - name: Check if feed.csv exists
        run: |
          if [ ! -f "misp_feed/feed.csv" ]; then
            echo "Error: feed.csv not found!"
            exit 1
          fi

      - name: Commit & push CSV feed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Pull & rebase, auto-stashing any local changes
          git pull --rebase --autostash origin "$(git rev-parse --abbrev-ref HEAD)"

          # Stage the CSV feed file
          git add "misp_feed/feed.csv"

          # Commit if there are staged changes
          git diff --staged --quiet || git commit -m "Update IOC feed: New data collected and processed"

          # Push via token auth
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git push origin "${{ github.ref_name }}"

