name: RSS to MISP Feed

on:
  schedule:
    - cron: '0 * * * *'   # hourly
  workflow_dispatch:

jobs:
  build-feed:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Validate config.json
        run: |
          jq empty config/config.json || exit 1

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download spaCy model
        run: python -m spacy download en_core_web_sm

      - name: Run collector & build feed
        run: |
          set -e
          python rss_ioc_collector.py > logs/workflow.log 2>&1

      - name: Read output directory from config.json
        id: feed-config
        run: |
          echo "OUTPUT=$(jq -r .output_base_dir < config/config.json)" >> $GITHUB_ENV

      - name: Commit & push CSV feed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Pull & rebase, auto-stashing any local changes
          git pull --rebase --autostash origin "$(git rev-parse --abbrev-ref HEAD)"

          # Stage the CSV feed file
          git add "${OUTPUT}/feed.csv"

          # Commit if there are staged changes
          git diff --staged --quiet || git commit -m "Update IOC feed: New data collected and processed"

          # Push via token auth
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git push origin "${{ github.ref_name }}"

