name: RSS to MISP Feed

on:
  schedule:
    - cron: '0 * * * *'  # Runs hourly
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-feed:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install spaCy model
      run: |
        python -m spacy download en_core_web_sm

    - name: Run RSS to MISP collector
      run: |
        python rss_ioc_collector.py
      env:
        FEED_URLS: ${{ secrets.FEED_URLS }}
        MAX_DAYS_OLD: ${{ secrets.MAX_DAYS_OLD }}
        OUTPUT_JSON_PATH: ${{ secrets.OUTPUT_JSON_PATH }}
        SEEN_IOCS_PATH: ${{ secrets.SEEN_IOCS_PATH }}
        WHITELIST_BY_FEED: ${{ secrets.WHITELIST_BY_FEED }}
        IOC_CONTEXT_KEYWORDS: ${{ secrets.IOC_CONTEXT_KEYWORDS }}
        IOC_PATTERNS: ${{ secrets.IOC_PATTERNS }}
