name: RSS to MISP Feed

on:
  push:                # Trigger the workflow on push events
    branches:
      - main           # Specify the branch to monitor for push events (e.g., "main")
  schedule:            # Trigger the workflow on a schedule
    - cron: '0 * * * *'   # Hourly
  workflow_dispatch:   # Allow manual triggering of the workflow

jobs:
  build-feed:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Validate config.json
        run: |
          jq empty config/config.json || exit 1

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download spaCy model
        run: python -m spacy download en_core_web_sm

      - name: Ensure logs directory exists
        run: mkdir -p logs

      - name: Run collector & build feed
        env:
          OTX_API_KEY: ${{ secrets.OTX_API_KEY }}
        run: |
          set -e
          python rss_ioc_collector.py

      - name: Print logs for debugging
        if: failure()
        run: cat ./logs/ioc_collector.log

      - name: Debug file structure
        run: |
          echo "Listing all files in the working directory:"
          ls -R
          echo "Listing files in the misp_feed directory:"
          ls misp_feed

      - name: Check if feed.csv exists
        run: |
          if [ ! -f "misp_feed/feed.csv" ]; then
            echo "Error: feed.csv not found!"
            exit 1
          fi

      - name: Commit & push CSV feed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          echo "Committing and pushing CSV feed..."
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Pull & rebase, auto-stashing any local changes
          git pull --rebase --autostash origin main

          # Stage the CSV feed file
          git add "misp_feed/feed.csv"

          # Stage output.json if it exists
          if [ -f "output/output.json" ]; then
            git add "output/output.json"
          else
            echo "Warning: output.json not found!"
          fi

          # Stage seen_iocs.json if it exists
          if [ -f "output/seen_iocs.json" ]; then
            git add "output/seen_iocs.json"
          else
            echo "Warning: seen_iocs.json not found!"
          fi
          
          # Stage ioc_collector.log if it exists
          if [ -f "logs/ioc_collector.log" ]; then
            git add "logs/ioc_collector.log"
          else
            echo "Warning: ioc_collector.log not found!"
          fi
          # Commit if there are staged changes
          git diff --staged --quiet || git commit -m "Update IOC feed and state files: New data collected and processed"

          # Push via token auth to the main branch
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git push origin main

